import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "UbuntuMono Nerd Font"
size = 16.0
