import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "None"
startup_mode = "Maximized"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font" 
bold_italic.family = "JetBrainsMono Nerd Font"

size = 15.0
